import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";

// Poppins fontunu import edelim
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Dinler Yapı Market",
  description: "Generated by Zafer Kanbur",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="container mx-auto">
          <NavBar />
          {children}
          <Toaster position="bottom-right" richColors />
          <Footer />
        </div>
      </body>
    </html>
  );
}
