import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner'
import NavBar from "@/components/navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Dinler Yapı Market",
  description: "Generated by Zafer Kanbur",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={montserrat.className}>

        <div className="container mx-auto">

          <NavBar />

          {children}
          <Toaster position="bottom-right" richColors />
        </div>

      </body>
    </html>
  );
}
